// src/constants/industries.ts

export const industries = [
  "Information Technology & Services",
  "Software Development",
  "Internet / Web Services",
  "Artificial Intelligence & Machine Learning",
  "Computer Hardware",
  "Telecommunications",
  "Financial Services",
  "Banking",
  "Accounting",
  "Insurance",
  "Venture Capital & Private Equity",
  "Management Consulting",
  "Manufacturing",
  "Construction",
  "Automotive",
  "Aerospace & Defense",
  "Chemicals",
  "Electrical / Electronics",
  "Healthcare & Hospitals",
  "Pharmaceuticals",
  "Biotechnology",
  "Medical Devices",
  "Research & Development",
  "Education & Training",
  "E-Learning",
  "Nonprofit Organization Management",
  "Government Administration",
  "Public Policy",
  "Retail",
  "Consumer Goods",
  "Fashion & Apparel",
  "Food & Beverages",
  "Hospitality",
  "Travel & Tourism",
  "Media & Broadcasting",
  "Marketing & Advertising",
  "Public Relations",
  "Entertainment",
  "Sports",
  "Publishing",
  "Oil & Energy",
  "Renewable Energy & Environment",
  "Utilities",
  "Mining & Metals",
  "Agriculture",
  "Transportation & Logistics",
  "Supply Chain & Warehousing",
  "Real Estate",
  "Facilities Services",
  "Gaming",
  "Design & Creative Services",
  "Human Resources",
  "Legal Services",
  "Security & Investigations",
  "Other",
] as const;

export type IndustryType = (typeof industries)[number];
